### ISSUE TITLE
You dont know who asked to use thread.

### ISSUE THREAD

**Issue by socksrust** [brunolemos/threadbot#1]
<img width="336" alt="screen shot 2018-07-03 at 22 28 45" src="https://user-images.githubusercontent.com/13947203/42251909-85e03536-7f10-11e8-9420-69154c617df8.png">

**Comment by brunolemos** [comment]
@jaburcodes that's by design.

If it says my name it would be similar to just asking it myself: I would become the annoying guy who always ask people to use thread.

**Comment by brunolemos** [comment]
I'll close since it seems you agreed 👍
